server:
  port: 8222

spring:
  application:
    name: service-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 使用服务发现路由

      # 路由规则
      routes:
        - id: service-workflow
          uri: lb://service-workflow
          predicates:
            - Path=/workflow/**
