# spring

spring:
  datasource:
    url: "jdbc:mysql://sh-cynosdbmysql-grp-mpnza716.sql.tencentcdb.com:25807/javase?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true"
    username: sphinx
    password: fxxkingC++

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  resources:
    static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/,
      - classpath:/public/,
      - file:D://Vue//javase_frontend//dist


# mybatis日志输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 静态资源