# spring

spring:
  datasource:
    url: "jdbc:mysql://sh-cynosdbmysql-grp-mpnza716.sql.tencentcdb.com:25807/javase?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8"
    username: sphinx
    password: fxxkingC++

  # redis
  redis:
    host: 129.211.80.11
    port: 6379
    jedis.pool.max-active: 8
    database: 1

  # nacos
  cloud.nacos.discovery.server-addr: 127.0.0.1:8848


# mybatis日志输出
mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl