# spring

spring:
  datasource:
    url: "jdbc:mysql://sh-cynosdbmysql-grp-mpnza716.sql.tencentcdb.com:25807/javase?serverTimezone=GMT%2B8"
    username: sphinx
    password: fxxkingC++

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


# mybatis日志输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl